default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  username: cybergarage
  password: 123456

development:
  <<: *default
  database: brew_development

test:
  <<: *default
  database: brew_test

production:
  <<: *default
  database: brew
