default: &default
  adapter: postgresql
  template: template0
  encoding: unicode
  reconnect: false
  pool: 10
  username: cybergarage
  password: 123456

development:
  <<: *default
  database: brew_development

test:
  <<: *default
  database: brew_test

production:
  <<: *default
  database: brew
